---
title: "Day 3 - Conditional & Loops"
author: "Andre Dextre"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(janitor)
library(skimr)


```


### `if` statements

```{r}
burrito <- 0.7

if (burrito > 2) {
  print("I love burritos!")
}
```

```{r}
my_ships <- c("Millenium Falcon", "X-wing", "Tile-Fighter", "Death Star")

str_detect(my_ships, pattern = "x")

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}
```

```{r}
tatooine_characters <- starwars %>% 
  filter(homeworld == "Tatooine")

#Use %in% operator to check for multiple positive matches

tatooine_endor_naboo <- starwars %>%
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))
#In words: Does the value in the homeworld variable for that row exist IN that vector c("Tatooine", "Naboo", "Endor").

```

## `if-else` statement
```{r}

pika <- 89.1

if (pika > 60) {
  print("mega pika")
} else {
  print("normal pika")
}


```

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print("this is a large marmot")
}
```

